export const API = 'https://api.mail.tm';
export const AVATARS_API = 'https://avatars.dicebear.com/api';
export const LOCAL_STORAGE_ACCOUNT_KEY = 'account';
export const APP_NAME = 'Temp-mail';
export const MESSAGES_REFRESH_DELAY = 4500;
export const TTF_MESSAGES_REFRESH_DELAY = 0;
export const AUTH_ERROR_DELAY = 1500;
export const DAYS_DECLENSIONS = ['day', 'days', 'days'];
export const DECLENSION_CASES = [2, 0, 1, 1, 1, 2];
